### PR TITLE
Initial set up

### PR DESCRIPTION
**Pull request by WyriHaximus**

### CODE REVIEW

**Review by JoshuaLuckers — APPROVED** [review]

**Comment by paulinevos** [comment]
Can you please also remove some lines.

**Comment by WyriHaximus** [comment]
@paulinevos Well, I haven't added GitHub.AE, so I'll add more 🎉

**Review by faizanakram99 — APPROVED** [review]
LGTM ✅

**Comment by DominikGrodl** [comment]
Looks fine, shit it to prod

**Pull request merged**
